apiVersion: v1
kind: Service
metadata:
  name: nginx-monitoring
  namespace: monitoring
  labels:
    app: nginx-monitoring
spec:
  selector:
    app: nginx-monitoring
  ports:
    - name: metrics
      port: 9113
      targetPort: metrics
